query GetPaymentMethods {
    getPaymentMethods {
        id
        provider
        paddlePaymentMethod {
            id
            customerId
            addressId
            businessId
        }
    }
}