apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xela-prod

resources:
  - ../../base
  - namespace.yaml
  - networkpolicies/

patchesStrategicMerge:
  - patches/replicas.yaml
  - patches/resource-limits.yaml
  - patches/high-availability.yaml

configMapGenerator:
  - name: xela-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn

secretGenerator:
  - name: xela-secrets
    behavior: merge
    envs:
      - .env.prod 