import { registerEnumType } from '@nestjs/graphql';

export enum PortfolioCreationMilestone {
    INITIALIZED = "INITIALIZED",
    CREDENTIALS_VERIFIED = "CREDENTIALS_VERIFIED",
    EXCHANGE_CONNECTED = "EXCHANGE_CONNECTED",
    ACCOUNT_FETCHED = "ACCOUNT_FETCHED",
    BALANCES_FETCHED = "BALANCES_FETCHED",
    PORTFOLIO_STORED = "PORTFOLIO_STORED",
    COMPLETED = "COMPLETED",
    VALIDATION_FAILED = "VALIDATION_FAILED",
    CREDENTIALS_FAILED = "CREDENTIALS_FAILED",
    CONNECTION_FAILED = "CONNECTION_FAILED",
    FETCH_FAILED = "FETCH_FAILED",
    STORAGE_FAILED = "STORAGE_FAILED",
    TIMEOUT_FAILED = "TIMEOUT_FAILED",
    RATE_LIMITED = "RATE_LIMITED",
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
    FAILED = "FAILED"
}


registerEnumType(PortfolioCreationMilestone, { name: 'PortfolioCreationMilestone', description: undefined })
