apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: xela
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
  - port: 5001
    targetPort: http
    name: http
  type: ClusterIP 