apiVersion: v1
kind: Service
metadata:
  name: message-broker
  labels:
    app.kubernetes.io/name: message-broker
    app.kubernetes.io/part-of: xela
spec:
  selector:
    app.kubernetes.io/name: message-broker
  ports:
  - port: 9092
    targetPort: kafka
    name: kafka
  - port: 29092
    targetPort: kafka-ext
    name: kafka-ext