apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: xela
spec:
  selector:
    app.kubernetes.io/name: zookeeper
  ports:
  - port: 22181
    targetPort: client
    name: client 