mutation Signup($data: CreateUserInput!) {
    signup(data: $data) {
        accessToken
        refreshToken
    }
}

mutation Login($data: LoginReqDto!) {
    login(data: $data) {
        accessToken
        refreshToken
    }
}

mutation VerifyAccount($data: VerifyDto!) {
    verifyAccount(data: $data) {
        accessToken
        refreshToken
    }
}

mutation RefreshToken($data: RefreshTokenInputDto!) {
    refreshToken(data: $data) {
        accessToken
        refreshToken
        expiresIn
    }
}

mutation Logout {
    logout
}