apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: xela
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/part-of: xela
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.0
        ports:
        - containerPort: 22181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "22181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
        readinessProbe:
          tcpSocket:
            port: 22181
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 22181
          initialDelaySeconds: 30
          periodSeconds: 15
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi 