apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-portfolio-consumer
spec:
  selector:
    matchLabels:
      app: crypto-portfolio-consumer
  template:
    metadata:
      labels:
        app: crypto-portfolio-consumer
    spec:
      containers:
      - name: crypto-portfolio-consumer
        image: ${REGISTRY_URL}/xela-crypto-portfolio-consumer:latest
        envFrom:
        - configMapRef:
            name: xela-config
        - secretRef:
            name: xela-secrets 