apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-consumer
spec:
  selector:
    matchLabels:
      app: embedding-consumer
  template:
    metadata:
      labels:
        app: embedding-consumer
    spec:
      containers:
      - name: embedding-consumer
        image: ${REGISTRY_URL}/xela-embedding-consumer:latest
        envFrom:
        - configMapRef:
            name: xela-config
        - secretRef:
            name: xela-secrets 