query GetEventCategories {
  getEventCategories {
    id
    name
    color
  }
}

mutation CreateEventCategory($data: CreateEventCategoryInput!) {
  createEventCategory(data: $data) {
    id
    name
    color
  }
}

mutation UpdateEventCategory($id: Int!, $data: UpdateEventCategoryInput!) {
  updateEventCategory(id: $id, data: $data) {
    id
    name
    color
  }
}

mutation RemoveEventCategory($id: Int!) {
  removeEventCategory(id: $id) {
    id
  }
} 