/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    mutation Login($data: LoginReqDto!) {\n        login(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n": typeof types.LoginDocument,
    "\n    query GetMe {\n        getMe {\n            email\n            id\n            name\n            otp\n            otpPurpose\n        }\n    }\n": typeof types.GetMeDocument,
    "\n    mutation Signup($data: CreateUserInput!) {\n        signup(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n": typeof types.SignupDocument,
    "\n    mutation VerifyAccount($data: VerifyDto!) {\n        verifyAccount(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n": typeof types.VerifyAccountDocument,
    "\n    mutation RefreshToken($data: RefreshTokenInputDto!) {\n        refreshToken(data: $data) {\n            accessToken\n            refreshToken\n            expiresIn\n        }\n    }\n": typeof types.RefreshTokenDocument,
    "\n    mutation Logout {\n        logout\n    }\n": typeof types.LogoutDocument,
    "\n    mutation CreateBankAccount($data: CreateBankAccountInput!) {\n        createBankAccount(data: $data) {\n            id\n            name\n            accountNumber\n            balance\n            createdAt\n        }\n    }\n": typeof types.CreateBankAccountDocument,
    "\n    query GetBankAccounts {\n        getBankAccounts {\n            id\n            name\n            accountNumber\n            balance\n            fullName\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetBankAccountsDocument,
    "\n    mutation CreateBankManager($data: CreateBankManagerInput!) {\n        createBankManager(data: $data) {\n            id\n            name\n            createdAt\n        }\n    }\n": typeof types.CreateBankManagerDocument,
    "\n    query GetBankManagers {\n        getBankManagers {\n            id\n            name\n            createdAt\n            updatedAt\n            autoBankManager {\n                thirdParty\n            }\n            banks {\n                name\n                accountName\n                accountNumber\n                balance\n                historicalBalances {\n                    balance\n                    time\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n": typeof types.GetBankManagersDocument,
    "\n    mutation CreateBankTransaction($data: CreateBankTransactionInput!) {\n        createBankTransaction(data: $data) {\n            id\n            amount\n            description\n            createdAt\n            bankId\n        }\n    }\n": typeof types.CreateBankTransactionDocument,
    "\n    query GetBankTransactions {\n        getBankTransactions {\n            id\n            amount\n            spentAmount\n            createdAt\n            description\n            bank {\n                name\n            }\n        }\n    }\n": typeof types.GetBankTransactionsDocument,
    "\n    mutation RemoveBankTransaction($id: Int!) {\n        removeBankTransaction(id: $id) {\n            id\n        }\n    }\n": typeof types.RemoveBankTransactionDocument,
    "\n    subscription NewHistoricalAssetProfit(\n        $data: GetHistoricalAssetProfitInput!\n    ) {\n        newHistoricalAssetProfit(data: $data) {\n            time\n            totalCostInQuoteQty\n            remainingQty\n            estimatedProfit\n        }\n    }\n": typeof types.NewHistoricalAssetProfitDocument,
    "\n    mutation CreateCryptoProfile($data: CreateCryptoPortfolioInput!) {\n        createCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n": typeof types.CreateCryptoProfileDocument,
    "\n    mutation CreateOKXCryptoPortfolio($data: CreateOKXCryptoPortfolioInput!) {\n        createOKXCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n": typeof types.CreateOkxCryptoPortfolioDocument,
    "\n    query GetCryptoPortfolios($timeFrame: String!) {\n        getCryptoPortfolios {\n            id\n            name\n            exchanges\n            tradingType\n            investmentCategoryName\n            latestHistoricalBalances(timeFrame: $timeFrame) {\n                changeBalance\n                changePercent\n                estimatedBalance\n            }\n            latestAssetProfits {\n                estimatedProfit\n                remainingQty\n                totalCostInQuoteQty\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n            balances {\n                id\n                balance\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n        }\n    }\n": typeof types.GetCryptoPortfoliosDocument,
    "\n    query GetHistoricalAssetProfits(\n        $data: GetHistoricalAssetProfitInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalAssetProfits(data: $data, pagination: $pagination) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n    }\n": typeof types.GetHistoricalAssetProfitsDocument,
    "\n    query GetHistoricalBalances(\n        $data: GetHistoricalBalanceInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalBalances(data: $data, pagination: $pagination) {\n            time\n            estimatedBalance\n            changePercent\n            changeBalance\n        }\n    }\n": typeof types.GetHistoricalBalancesDocument,
    "\n    query GetAsset(\n        $pagination: PaginationInput!\n        $getAssetPriceData: GetAssetPriceInput!\n        $getAssetProfitData: GetHistoricalAssetProfitInput!\n        $getAssetInfoData: GetAssetInfoInput!\n    ) {\n        getHistoricalAssetProfits(\n            data: $getAssetProfitData\n            pagination: $pagination\n        ) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n\n        getAssetPrices(data: $getAssetPriceData, pagination: $pagination) {\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n        getAssetInfo(data: $getAssetInfoData) {\n            logo\n            desc\n            category\n            symbol\n            name\n        }\n    }\n": typeof types.GetAssetDocument,
    "\n    subscription NewAssetPrice($data: GetAssetPriceInput!) {\n        newAssetPrice(data: $data) {\n            assetInfoId\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n    }\n": typeof types.NewAssetPriceDocument,
    "\n    subscription NewHistoricalCryptoBalance(\n        $data: GetHistoricalBalancesInput!\n    ) {\n        newHistoricalCryptoBalance(data: $data) {\n            cryptoPortfolioId\n            time\n            estimatedBalance\n            changeBalance\n            changePercent\n        }\n    }\n": typeof types.NewHistoricalCryptoBalanceDocument,
    "\n    query GetCreatePortfolioExecutions($userId: Float!) {\n        getCreatePortfolioExecutions(userId: $userId) {\n            id\n            status\n            time\n        }\n    }\n": typeof types.GetCreatePortfolioExecutionsDocument,
    "\n    subscription OnPortfolioCreationStatus {\n        onCreatePortfolioExecution {\n            id\n            userId\n            status\n            time\n        }\n    }\n": typeof types.OnPortfolioCreationStatusDocument,
    "\n    query GetTrades($data: GetTradeInput!) {\n        getTrades(data: $data) {\n            cryptoPortfolio {\n                id\n                name\n                exchanges\n            }\n            time\n            price\n            qty\n            quoteQty\n            commission\n            commissionAsset\n            isBuyer\n        }\n    }\n": typeof types.GetTradesDocument,
    "\n    query GetExpenseCategories(\n        $name: String\n        $startDate: DateTime\n        $endDate: DateTime\n        $month: Int\n        $year: Int\n    ) {\n        getExpenseCategories(name: $name) {\n            color\n            description\n            name\n            id\n            countExpenses\n            totalSpentAmounts(startDate: $startDate, endDate: $endDate) {\n                amount\n                month\n                year\n            }\n            monthlyTargets(month: $month, year: $year) {\n                month\n                year\n                target\n            }\n        }\n    }\n": typeof types.GetExpenseCategoriesDocument,
    "\n    mutation CreateExpenseCategory($data: CreateExpenseCategoryInput!) {\n        createExpenseCategory(data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n": typeof types.CreateExpenseCategoryDocument,
    "\n    mutation UpdateExpenseCategory(\n        $id: String!\n        $data: UpdateExpenseCategoryInput!\n    ) {\n        updateExpenseCategory(id: $id, data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n": typeof types.UpdateExpenseCategoryDocument,
    "\n    mutation RemoveExpenseCategory($id: String!) {\n        removeExpenseCategory(id: $id) {\n            id\n        }\n    }\n": typeof types.RemoveExpenseCategoryDocument,
    "\n    query GetMonthlyTargets($categoryId: String!, $month: Int, $year: Int) {\n        getMonthlyTargets(categoryId: $categoryId, month: $month, year: $year) {\n            target\n            month\n            year\n        }\n    }\n": typeof types.GetMonthlyTargetsDocument,
    "\n    mutation CreateMonthlyTarget($data: CreateMonthlyTargetInput!) {\n        createMonthlyTarget(data: $data) {\n            categoryId\n        }\n    }\n": typeof types.CreateMonthlyTargetDocument,
    "\n    mutation UpdateMonthlyTarget(\n        $id: String!\n        $data: UpdateMonthlyTargetInput!\n    ) {\n        updateMonthlyTarget(id: $id, data: $data) {\n            categoryId\n        }\n    }\n": typeof types.UpdateMonthlyTargetDocument,
    "\n    query GetExpenses($startDate: DateTime, $endDate: DateTime) {\n        getExpenses(startDate: $startDate, endDate: $endDate) {\n            id\n            category {\n                id\n                color\n                name\n            }\n            transaction {\n                id\n                amount\n                spentAmount\n                description\n                createdAt\n                bank {\n                    name\n                }\n            }\n            createdAt\n            description\n            amount\n            name\n        }\n    }\n": typeof types.GetExpensesDocument,
    "\n    query GetSuggestedExpenses($data: SuggestExpenseInput!) {\n        getSuggestedExpenses(data: $data) {\n            amount\n            name\n            bankTransactionId\n            categoryId\n            description\n        }\n    }\n": typeof types.GetSuggestedExpensesDocument,
    "\n    mutation CreateExpense($data: CreateExpenseInput!) {\n        createExpense(data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n": typeof types.CreateExpenseDocument,
    "\n    mutation UpdateExpense($id: String!, $data: UpdateExpenseInput!) {\n        updateExpense(id: $id, data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n": typeof types.UpdateExpenseDocument,
    "\n    mutation RemoveExpense($id: String!) {\n        removeExpense(id: $id) {\n            id\n            description\n            amount\n            name\n        }\n    }\n": typeof types.RemoveExpenseDocument,
    "\n    mutation RemoveExpenses($ids: [String!]!) {\n        removeExpenses(ids: $ids)\n    }\n": typeof types.RemoveExpensesDocument,
    "\n    query GetMembershipPlans {\n        getMembershipPlans {\n            id\n            name\n            description\n            createdAt\n            updatedAt\n            prices {\n                id\n                billingCycle {\n                    frequency\n                    interval\n                }\n                trialPeriod {\n                    frequency\n                    interval\n                }\n                unitPrice {\n                    amount\n                    currencyCode\n                }\n            }\n            membershipFeatures {\n                feature {\n                    type\n                }\n            }\n        }\n    }\n": typeof types.GetMembershipPlansDocument,
    "\n    query GetMyMembershipSubscriptions {\n        myMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n            paymentTransactions {\n                id\n                amount\n                currency\n                status\n                createdAt\n            }\n        }\n    }\n": typeof types.GetMyMembershipSubscriptionsDocument,
    "\n    query GetMyActiveMembershipSubscriptions {\n        myActiveMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n        }\n    }\n": typeof types.GetMyActiveMembershipSubscriptionsDocument,
    "\n    mutation CancelMembershipSubscription($id: String!) {\n        cancelPaddleSubscription(id: $id) {\n            id\n            status\n            endDate\n        }\n    }\n": typeof types.CancelMembershipSubscriptionDocument,
    "\n    mutation UpdateMembershipSubscription(\n        $id: String!\n        $data: UpdateSubscriptionDto!\n    ) {\n        updateMembershipSubscription(id: $id, data: $data) {\n            id\n            status\n            planId\n            endDate\n        }\n    }\n": typeof types.UpdateMembershipSubscriptionDocument,
    "\n    mutation ReactivatePaddleSubscription($id: String!) {\n        reactivatePaddleSubscription(id: $id) {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.ReactivatePaddleSubscriptionDocument,
    "\n    subscription OnMembershipSubscriptionUpdated {\n        onMembershipSubscriptionUpdated {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.OnMembershipSubscriptionUpdatedDocument,
    "\n    query GetPaymentMethods {\n        getPaymentMethods {\n            id\n            provider\n            paddlePaymentMethod {\n                id\n                customerId\n                addressId\n                businessId\n            }\n        }\n    }\n": typeof types.GetPaymentMethodsDocument,
    "\n    query GetEventCategories {\n        getEventCategories {\n            id\n            name\n            color\n        }\n    }\n": typeof types.GetEventCategoriesDocument,
    "\n    mutation CreateEventCategory($data: CreateEventCategoryInput!) {\n        createEventCategory(data: $data) {\n            id\n            name\n            color\n        }\n    }\n": typeof types.CreateEventCategoryDocument,
    "\n    mutation UpdateEventCategory($id: Int!, $data: UpdateEventCategoryInput!) {\n        updateEventCategory(id: $id, data: $data) {\n            id\n            name\n            color\n        }\n    }\n": typeof types.UpdateEventCategoryDocument,
    "\n    mutation RemoveEventCategory($id: Int!) {\n        removeEventCategory(id: $id) {\n            id\n        }\n    }\n": typeof types.RemoveEventCategoryDocument,
    "\n    query GetRecurrenceTemplates {\n        getRecurrenceTemplates {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n            events {\n                id\n                name\n                description\n                startDate\n                endDate\n                allDay\n                color\n                categoryId\n                reminderMinutes\n                category {\n                    id\n                    name\n                    color\n                }\n            }\n        }\n    }\n": typeof types.GetRecurrenceTemplatesDocument,
    "\n    query GetRecurrenceTemplate($id: Int!) {\n        getRecurrenceTemplate(id: $id) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetRecurrenceTemplateDocument,
    "\n    mutation UpdateRecurrenceTemplate(\n        $id: Int!\n        $data: UpdateEventRecurrenceInput!\n    ) {\n        updateRecurrenceTemplate(id: $id, data: $data) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.UpdateRecurrenceTemplateDocument,
    "\n    mutation DeleteRecurrenceTemplate($id: Int!) {\n        deleteRecurrenceTemplate(id: $id) {\n            id\n        }\n    }\n": typeof types.DeleteRecurrenceTemplateDocument,
    "\n    query GetEvents($startDate: DateTime, $endDate: DateTime) {\n        getEvents(startDate: $startDate, endDate: $endDate) {\n            id\n            name\n            startDate\n            endDate\n            allDay\n            color\n            description\n            category {\n                id\n                name\n                color\n            }\n            recurrence {\n                type\n                interval\n                daysOfWeek\n                dayOfMonth\n                weekOfMonth\n                dayOfWeek\n                endDate\n                endCount\n            }\n        }\n    }\n": typeof types.GetEventsDocument,
    "\n    mutation CreateEvent($data: CreateEventInput!) {\n        createEvent(data: $data) {\n            id\n            name\n            startDate\n            endDate\n            category {\n                id\n            }\n            recurrence {\n                id\n            }\n        }\n    }\n": typeof types.CreateEventDocument,
    "\n    mutation UpdateEvent($id: Int!, $data: UpdateEventInput!) {\n        updateEvent(id: $id, data: $data) {\n            id\n            name\n            startDate\n            endDate\n        }\n    }\n": typeof types.UpdateEventDocument,
    "\n    mutation RemoveEvent($id: Int!) {\n        removeEvent(id: $id) {\n            id\n        }\n    }\n": typeof types.RemoveEventDocument,
};
const documents: Documents = {
    "\n    mutation Login($data: LoginReqDto!) {\n        login(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n": types.LoginDocument,
    "\n    query GetMe {\n        getMe {\n            email\n            id\n            name\n            otp\n            otpPurpose\n        }\n    }\n": types.GetMeDocument,
    "\n    mutation Signup($data: CreateUserInput!) {\n        signup(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n": types.SignupDocument,
    "\n    mutation VerifyAccount($data: VerifyDto!) {\n        verifyAccount(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n": types.VerifyAccountDocument,
    "\n    mutation RefreshToken($data: RefreshTokenInputDto!) {\n        refreshToken(data: $data) {\n            accessToken\n            refreshToken\n            expiresIn\n        }\n    }\n": types.RefreshTokenDocument,
    "\n    mutation Logout {\n        logout\n    }\n": types.LogoutDocument,
    "\n    mutation CreateBankAccount($data: CreateBankAccountInput!) {\n        createBankAccount(data: $data) {\n            id\n            name\n            accountNumber\n            balance\n            createdAt\n        }\n    }\n": types.CreateBankAccountDocument,
    "\n    query GetBankAccounts {\n        getBankAccounts {\n            id\n            name\n            accountNumber\n            balance\n            fullName\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetBankAccountsDocument,
    "\n    mutation CreateBankManager($data: CreateBankManagerInput!) {\n        createBankManager(data: $data) {\n            id\n            name\n            createdAt\n        }\n    }\n": types.CreateBankManagerDocument,
    "\n    query GetBankManagers {\n        getBankManagers {\n            id\n            name\n            createdAt\n            updatedAt\n            autoBankManager {\n                thirdParty\n            }\n            banks {\n                name\n                accountName\n                accountNumber\n                balance\n                historicalBalances {\n                    balance\n                    time\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n": types.GetBankManagersDocument,
    "\n    mutation CreateBankTransaction($data: CreateBankTransactionInput!) {\n        createBankTransaction(data: $data) {\n            id\n            amount\n            description\n            createdAt\n            bankId\n        }\n    }\n": types.CreateBankTransactionDocument,
    "\n    query GetBankTransactions {\n        getBankTransactions {\n            id\n            amount\n            spentAmount\n            createdAt\n            description\n            bank {\n                name\n            }\n        }\n    }\n": types.GetBankTransactionsDocument,
    "\n    mutation RemoveBankTransaction($id: Int!) {\n        removeBankTransaction(id: $id) {\n            id\n        }\n    }\n": types.RemoveBankTransactionDocument,
    "\n    subscription NewHistoricalAssetProfit(\n        $data: GetHistoricalAssetProfitInput!\n    ) {\n        newHistoricalAssetProfit(data: $data) {\n            time\n            totalCostInQuoteQty\n            remainingQty\n            estimatedProfit\n        }\n    }\n": types.NewHistoricalAssetProfitDocument,
    "\n    mutation CreateCryptoProfile($data: CreateCryptoPortfolioInput!) {\n        createCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n": types.CreateCryptoProfileDocument,
    "\n    mutation CreateOKXCryptoPortfolio($data: CreateOKXCryptoPortfolioInput!) {\n        createOKXCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n": types.CreateOkxCryptoPortfolioDocument,
    "\n    query GetCryptoPortfolios($timeFrame: String!) {\n        getCryptoPortfolios {\n            id\n            name\n            exchanges\n            tradingType\n            investmentCategoryName\n            latestHistoricalBalances(timeFrame: $timeFrame) {\n                changeBalance\n                changePercent\n                estimatedBalance\n            }\n            latestAssetProfits {\n                estimatedProfit\n                remainingQty\n                totalCostInQuoteQty\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n            balances {\n                id\n                balance\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n        }\n    }\n": types.GetCryptoPortfoliosDocument,
    "\n    query GetHistoricalAssetProfits(\n        $data: GetHistoricalAssetProfitInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalAssetProfits(data: $data, pagination: $pagination) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n    }\n": types.GetHistoricalAssetProfitsDocument,
    "\n    query GetHistoricalBalances(\n        $data: GetHistoricalBalanceInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalBalances(data: $data, pagination: $pagination) {\n            time\n            estimatedBalance\n            changePercent\n            changeBalance\n        }\n    }\n": types.GetHistoricalBalancesDocument,
    "\n    query GetAsset(\n        $pagination: PaginationInput!\n        $getAssetPriceData: GetAssetPriceInput!\n        $getAssetProfitData: GetHistoricalAssetProfitInput!\n        $getAssetInfoData: GetAssetInfoInput!\n    ) {\n        getHistoricalAssetProfits(\n            data: $getAssetProfitData\n            pagination: $pagination\n        ) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n\n        getAssetPrices(data: $getAssetPriceData, pagination: $pagination) {\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n        getAssetInfo(data: $getAssetInfoData) {\n            logo\n            desc\n            category\n            symbol\n            name\n        }\n    }\n": types.GetAssetDocument,
    "\n    subscription NewAssetPrice($data: GetAssetPriceInput!) {\n        newAssetPrice(data: $data) {\n            assetInfoId\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n    }\n": types.NewAssetPriceDocument,
    "\n    subscription NewHistoricalCryptoBalance(\n        $data: GetHistoricalBalancesInput!\n    ) {\n        newHistoricalCryptoBalance(data: $data) {\n            cryptoPortfolioId\n            time\n            estimatedBalance\n            changeBalance\n            changePercent\n        }\n    }\n": types.NewHistoricalCryptoBalanceDocument,
    "\n    query GetCreatePortfolioExecutions($userId: Float!) {\n        getCreatePortfolioExecutions(userId: $userId) {\n            id\n            status\n            time\n        }\n    }\n": types.GetCreatePortfolioExecutionsDocument,
    "\n    subscription OnPortfolioCreationStatus {\n        onCreatePortfolioExecution {\n            id\n            userId\n            status\n            time\n        }\n    }\n": types.OnPortfolioCreationStatusDocument,
    "\n    query GetTrades($data: GetTradeInput!) {\n        getTrades(data: $data) {\n            cryptoPortfolio {\n                id\n                name\n                exchanges\n            }\n            time\n            price\n            qty\n            quoteQty\n            commission\n            commissionAsset\n            isBuyer\n        }\n    }\n": types.GetTradesDocument,
    "\n    query GetExpenseCategories(\n        $name: String\n        $startDate: DateTime\n        $endDate: DateTime\n        $month: Int\n        $year: Int\n    ) {\n        getExpenseCategories(name: $name) {\n            color\n            description\n            name\n            id\n            countExpenses\n            totalSpentAmounts(startDate: $startDate, endDate: $endDate) {\n                amount\n                month\n                year\n            }\n            monthlyTargets(month: $month, year: $year) {\n                month\n                year\n                target\n            }\n        }\n    }\n": types.GetExpenseCategoriesDocument,
    "\n    mutation CreateExpenseCategory($data: CreateExpenseCategoryInput!) {\n        createExpenseCategory(data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n": types.CreateExpenseCategoryDocument,
    "\n    mutation UpdateExpenseCategory(\n        $id: String!\n        $data: UpdateExpenseCategoryInput!\n    ) {\n        updateExpenseCategory(id: $id, data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n": types.UpdateExpenseCategoryDocument,
    "\n    mutation RemoveExpenseCategory($id: String!) {\n        removeExpenseCategory(id: $id) {\n            id\n        }\n    }\n": types.RemoveExpenseCategoryDocument,
    "\n    query GetMonthlyTargets($categoryId: String!, $month: Int, $year: Int) {\n        getMonthlyTargets(categoryId: $categoryId, month: $month, year: $year) {\n            target\n            month\n            year\n        }\n    }\n": types.GetMonthlyTargetsDocument,
    "\n    mutation CreateMonthlyTarget($data: CreateMonthlyTargetInput!) {\n        createMonthlyTarget(data: $data) {\n            categoryId\n        }\n    }\n": types.CreateMonthlyTargetDocument,
    "\n    mutation UpdateMonthlyTarget(\n        $id: String!\n        $data: UpdateMonthlyTargetInput!\n    ) {\n        updateMonthlyTarget(id: $id, data: $data) {\n            categoryId\n        }\n    }\n": types.UpdateMonthlyTargetDocument,
    "\n    query GetExpenses($startDate: DateTime, $endDate: DateTime) {\n        getExpenses(startDate: $startDate, endDate: $endDate) {\n            id\n            category {\n                id\n                color\n                name\n            }\n            transaction {\n                id\n                amount\n                spentAmount\n                description\n                createdAt\n                bank {\n                    name\n                }\n            }\n            createdAt\n            description\n            amount\n            name\n        }\n    }\n": types.GetExpensesDocument,
    "\n    query GetSuggestedExpenses($data: SuggestExpenseInput!) {\n        getSuggestedExpenses(data: $data) {\n            amount\n            name\n            bankTransactionId\n            categoryId\n            description\n        }\n    }\n": types.GetSuggestedExpensesDocument,
    "\n    mutation CreateExpense($data: CreateExpenseInput!) {\n        createExpense(data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n": types.CreateExpenseDocument,
    "\n    mutation UpdateExpense($id: String!, $data: UpdateExpenseInput!) {\n        updateExpense(id: $id, data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n": types.UpdateExpenseDocument,
    "\n    mutation RemoveExpense($id: String!) {\n        removeExpense(id: $id) {\n            id\n            description\n            amount\n            name\n        }\n    }\n": types.RemoveExpenseDocument,
    "\n    mutation RemoveExpenses($ids: [String!]!) {\n        removeExpenses(ids: $ids)\n    }\n": types.RemoveExpensesDocument,
    "\n    query GetMembershipPlans {\n        getMembershipPlans {\n            id\n            name\n            description\n            createdAt\n            updatedAt\n            prices {\n                id\n                billingCycle {\n                    frequency\n                    interval\n                }\n                trialPeriod {\n                    frequency\n                    interval\n                }\n                unitPrice {\n                    amount\n                    currencyCode\n                }\n            }\n            membershipFeatures {\n                feature {\n                    type\n                }\n            }\n        }\n    }\n": types.GetMembershipPlansDocument,
    "\n    query GetMyMembershipSubscriptions {\n        myMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n            paymentTransactions {\n                id\n                amount\n                currency\n                status\n                createdAt\n            }\n        }\n    }\n": types.GetMyMembershipSubscriptionsDocument,
    "\n    query GetMyActiveMembershipSubscriptions {\n        myActiveMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n        }\n    }\n": types.GetMyActiveMembershipSubscriptionsDocument,
    "\n    mutation CancelMembershipSubscription($id: String!) {\n        cancelPaddleSubscription(id: $id) {\n            id\n            status\n            endDate\n        }\n    }\n": types.CancelMembershipSubscriptionDocument,
    "\n    mutation UpdateMembershipSubscription(\n        $id: String!\n        $data: UpdateSubscriptionDto!\n    ) {\n        updateMembershipSubscription(id: $id, data: $data) {\n            id\n            status\n            planId\n            endDate\n        }\n    }\n": types.UpdateMembershipSubscriptionDocument,
    "\n    mutation ReactivatePaddleSubscription($id: String!) {\n        reactivatePaddleSubscription(id: $id) {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n": types.ReactivatePaddleSubscriptionDocument,
    "\n    subscription OnMembershipSubscriptionUpdated {\n        onMembershipSubscriptionUpdated {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n": types.OnMembershipSubscriptionUpdatedDocument,
    "\n    query GetPaymentMethods {\n        getPaymentMethods {\n            id\n            provider\n            paddlePaymentMethod {\n                id\n                customerId\n                addressId\n                businessId\n            }\n        }\n    }\n": types.GetPaymentMethodsDocument,
    "\n    query GetEventCategories {\n        getEventCategories {\n            id\n            name\n            color\n        }\n    }\n": types.GetEventCategoriesDocument,
    "\n    mutation CreateEventCategory($data: CreateEventCategoryInput!) {\n        createEventCategory(data: $data) {\n            id\n            name\n            color\n        }\n    }\n": types.CreateEventCategoryDocument,
    "\n    mutation UpdateEventCategory($id: Int!, $data: UpdateEventCategoryInput!) {\n        updateEventCategory(id: $id, data: $data) {\n            id\n            name\n            color\n        }\n    }\n": types.UpdateEventCategoryDocument,
    "\n    mutation RemoveEventCategory($id: Int!) {\n        removeEventCategory(id: $id) {\n            id\n        }\n    }\n": types.RemoveEventCategoryDocument,
    "\n    query GetRecurrenceTemplates {\n        getRecurrenceTemplates {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n            events {\n                id\n                name\n                description\n                startDate\n                endDate\n                allDay\n                color\n                categoryId\n                reminderMinutes\n                category {\n                    id\n                    name\n                    color\n                }\n            }\n        }\n    }\n": types.GetRecurrenceTemplatesDocument,
    "\n    query GetRecurrenceTemplate($id: Int!) {\n        getRecurrenceTemplate(id: $id) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetRecurrenceTemplateDocument,
    "\n    mutation UpdateRecurrenceTemplate(\n        $id: Int!\n        $data: UpdateEventRecurrenceInput!\n    ) {\n        updateRecurrenceTemplate(id: $id, data: $data) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n": types.UpdateRecurrenceTemplateDocument,
    "\n    mutation DeleteRecurrenceTemplate($id: Int!) {\n        deleteRecurrenceTemplate(id: $id) {\n            id\n        }\n    }\n": types.DeleteRecurrenceTemplateDocument,
    "\n    query GetEvents($startDate: DateTime, $endDate: DateTime) {\n        getEvents(startDate: $startDate, endDate: $endDate) {\n            id\n            name\n            startDate\n            endDate\n            allDay\n            color\n            description\n            category {\n                id\n                name\n                color\n            }\n            recurrence {\n                type\n                interval\n                daysOfWeek\n                dayOfMonth\n                weekOfMonth\n                dayOfWeek\n                endDate\n                endCount\n            }\n        }\n    }\n": types.GetEventsDocument,
    "\n    mutation CreateEvent($data: CreateEventInput!) {\n        createEvent(data: $data) {\n            id\n            name\n            startDate\n            endDate\n            category {\n                id\n            }\n            recurrence {\n                id\n            }\n        }\n    }\n": types.CreateEventDocument,
    "\n    mutation UpdateEvent($id: Int!, $data: UpdateEventInput!) {\n        updateEvent(id: $id, data: $data) {\n            id\n            name\n            startDate\n            endDate\n        }\n    }\n": types.UpdateEventDocument,
    "\n    mutation RemoveEvent($id: Int!) {\n        removeEvent(id: $id) {\n            id\n        }\n    }\n": types.RemoveEventDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation Login($data: LoginReqDto!) {\n        login(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n"): (typeof documents)["\n    mutation Login($data: LoginReqDto!) {\n        login(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetMe {\n        getMe {\n            email\n            id\n            name\n            otp\n            otpPurpose\n        }\n    }\n"): (typeof documents)["\n    query GetMe {\n        getMe {\n            email\n            id\n            name\n            otp\n            otpPurpose\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation Signup($data: CreateUserInput!) {\n        signup(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n"): (typeof documents)["\n    mutation Signup($data: CreateUserInput!) {\n        signup(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation VerifyAccount($data: VerifyDto!) {\n        verifyAccount(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n"): (typeof documents)["\n    mutation VerifyAccount($data: VerifyDto!) {\n        verifyAccount(data: $data) {\n            accessToken\n            refreshToken\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RefreshToken($data: RefreshTokenInputDto!) {\n        refreshToken(data: $data) {\n            accessToken\n            refreshToken\n            expiresIn\n        }\n    }\n"): (typeof documents)["\n    mutation RefreshToken($data: RefreshTokenInputDto!) {\n        refreshToken(data: $data) {\n            accessToken\n            refreshToken\n            expiresIn\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation Logout {\n        logout\n    }\n"): (typeof documents)["\n    mutation Logout {\n        logout\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateBankAccount($data: CreateBankAccountInput!) {\n        createBankAccount(data: $data) {\n            id\n            name\n            accountNumber\n            balance\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    mutation CreateBankAccount($data: CreateBankAccountInput!) {\n        createBankAccount(data: $data) {\n            id\n            name\n            accountNumber\n            balance\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBankAccounts {\n        getBankAccounts {\n            id\n            name\n            accountNumber\n            balance\n            fullName\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetBankAccounts {\n        getBankAccounts {\n            id\n            name\n            accountNumber\n            balance\n            fullName\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateBankManager($data: CreateBankManagerInput!) {\n        createBankManager(data: $data) {\n            id\n            name\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    mutation CreateBankManager($data: CreateBankManagerInput!) {\n        createBankManager(data: $data) {\n            id\n            name\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBankManagers {\n        getBankManagers {\n            id\n            name\n            createdAt\n            updatedAt\n            autoBankManager {\n                thirdParty\n            }\n            banks {\n                name\n                accountName\n                accountNumber\n                balance\n                historicalBalances {\n                    balance\n                    time\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetBankManagers {\n        getBankManagers {\n            id\n            name\n            createdAt\n            updatedAt\n            autoBankManager {\n                thirdParty\n            }\n            banks {\n                name\n                accountName\n                accountNumber\n                balance\n                historicalBalances {\n                    balance\n                    time\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateBankTransaction($data: CreateBankTransactionInput!) {\n        createBankTransaction(data: $data) {\n            id\n            amount\n            description\n            createdAt\n            bankId\n        }\n    }\n"): (typeof documents)["\n    mutation CreateBankTransaction($data: CreateBankTransactionInput!) {\n        createBankTransaction(data: $data) {\n            id\n            amount\n            description\n            createdAt\n            bankId\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBankTransactions {\n        getBankTransactions {\n            id\n            amount\n            spentAmount\n            createdAt\n            description\n            bank {\n                name\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetBankTransactions {\n        getBankTransactions {\n            id\n            amount\n            spentAmount\n            createdAt\n            description\n            bank {\n                name\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RemoveBankTransaction($id: Int!) {\n        removeBankTransaction(id: $id) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation RemoveBankTransaction($id: Int!) {\n        removeBankTransaction(id: $id) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription NewHistoricalAssetProfit(\n        $data: GetHistoricalAssetProfitInput!\n    ) {\n        newHistoricalAssetProfit(data: $data) {\n            time\n            totalCostInQuoteQty\n            remainingQty\n            estimatedProfit\n        }\n    }\n"): (typeof documents)["\n    subscription NewHistoricalAssetProfit(\n        $data: GetHistoricalAssetProfitInput!\n    ) {\n        newHistoricalAssetProfit(data: $data) {\n            time\n            totalCostInQuoteQty\n            remainingQty\n            estimatedProfit\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateCryptoProfile($data: CreateCryptoPortfolioInput!) {\n        createCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n"): (typeof documents)["\n    mutation CreateCryptoProfile($data: CreateCryptoPortfolioInput!) {\n        createCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateOKXCryptoPortfolio($data: CreateOKXCryptoPortfolioInput!) {\n        createOKXCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n"): (typeof documents)["\n    mutation CreateOKXCryptoPortfolio($data: CreateOKXCryptoPortfolioInput!) {\n        createOKXCryptoPortfolio(data: $data) {\n            userId\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCryptoPortfolios($timeFrame: String!) {\n        getCryptoPortfolios {\n            id\n            name\n            exchanges\n            tradingType\n            investmentCategoryName\n            latestHistoricalBalances(timeFrame: $timeFrame) {\n                changeBalance\n                changePercent\n                estimatedBalance\n            }\n            latestAssetProfits {\n                estimatedProfit\n                remainingQty\n                totalCostInQuoteQty\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n            balances {\n                id\n                balance\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetCryptoPortfolios($timeFrame: String!) {\n        getCryptoPortfolios {\n            id\n            name\n            exchanges\n            tradingType\n            investmentCategoryName\n            latestHistoricalBalances(timeFrame: $timeFrame) {\n                changeBalance\n                changePercent\n                estimatedBalance\n            }\n            latestAssetProfits {\n                estimatedProfit\n                remainingQty\n                totalCostInQuoteQty\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n            balances {\n                id\n                balance\n                cryptoPortfolio {\n                    id\n                    exchanges\n                    name\n                }\n                assetInfo {\n                    id\n                    logo\n                    lastPrice\n                    symbol\n                    tag\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetHistoricalAssetProfits(\n        $data: GetHistoricalAssetProfitInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalAssetProfits(data: $data, pagination: $pagination) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n    }\n"): (typeof documents)["\n    query GetHistoricalAssetProfits(\n        $data: GetHistoricalAssetProfitInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalAssetProfits(data: $data, pagination: $pagination) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetHistoricalBalances(\n        $data: GetHistoricalBalanceInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalBalances(data: $data, pagination: $pagination) {\n            time\n            estimatedBalance\n            changePercent\n            changeBalance\n        }\n    }\n"): (typeof documents)["\n    query GetHistoricalBalances(\n        $data: GetHistoricalBalanceInput!\n        $pagination: PaginationInput!\n    ) {\n        getHistoricalBalances(data: $data, pagination: $pagination) {\n            time\n            estimatedBalance\n            changePercent\n            changeBalance\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetAsset(\n        $pagination: PaginationInput!\n        $getAssetPriceData: GetAssetPriceInput!\n        $getAssetProfitData: GetHistoricalAssetProfitInput!\n        $getAssetInfoData: GetAssetInfoInput!\n    ) {\n        getHistoricalAssetProfits(\n            data: $getAssetProfitData\n            pagination: $pagination\n        ) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n\n        getAssetPrices(data: $getAssetPriceData, pagination: $pagination) {\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n        getAssetInfo(data: $getAssetInfoData) {\n            logo\n            desc\n            category\n            symbol\n            name\n        }\n    }\n"): (typeof documents)["\n    query GetAsset(\n        $pagination: PaginationInput!\n        $getAssetPriceData: GetAssetPriceInput!\n        $getAssetProfitData: GetHistoricalAssetProfitInput!\n        $getAssetInfoData: GetAssetInfoInput!\n    ) {\n        getHistoricalAssetProfits(\n            data: $getAssetProfitData\n            pagination: $pagination\n        ) {\n            time\n            estimatedProfit\n            remainingQty\n            totalCostInQuoteQty\n        }\n\n        getAssetPrices(data: $getAssetPriceData, pagination: $pagination) {\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n        getAssetInfo(data: $getAssetInfoData) {\n            logo\n            desc\n            category\n            symbol\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription NewAssetPrice($data: GetAssetPriceInput!) {\n        newAssetPrice(data: $data) {\n            assetInfoId\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n    }\n"): (typeof documents)["\n    subscription NewAssetPrice($data: GetAssetPriceInput!) {\n        newAssetPrice(data: $data) {\n            assetInfoId\n            open_time\n            openPrice\n            closePrice\n            highPrice\n            lowPrice\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription NewHistoricalCryptoBalance(\n        $data: GetHistoricalBalancesInput!\n    ) {\n        newHistoricalCryptoBalance(data: $data) {\n            cryptoPortfolioId\n            time\n            estimatedBalance\n            changeBalance\n            changePercent\n        }\n    }\n"): (typeof documents)["\n    subscription NewHistoricalCryptoBalance(\n        $data: GetHistoricalBalancesInput!\n    ) {\n        newHistoricalCryptoBalance(data: $data) {\n            cryptoPortfolioId\n            time\n            estimatedBalance\n            changeBalance\n            changePercent\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCreatePortfolioExecutions($userId: Float!) {\n        getCreatePortfolioExecutions(userId: $userId) {\n            id\n            status\n            time\n        }\n    }\n"): (typeof documents)["\n    query GetCreatePortfolioExecutions($userId: Float!) {\n        getCreatePortfolioExecutions(userId: $userId) {\n            id\n            status\n            time\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription OnPortfolioCreationStatus {\n        onCreatePortfolioExecution {\n            id\n            userId\n            status\n            time\n        }\n    }\n"): (typeof documents)["\n    subscription OnPortfolioCreationStatus {\n        onCreatePortfolioExecution {\n            id\n            userId\n            status\n            time\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetTrades($data: GetTradeInput!) {\n        getTrades(data: $data) {\n            cryptoPortfolio {\n                id\n                name\n                exchanges\n            }\n            time\n            price\n            qty\n            quoteQty\n            commission\n            commissionAsset\n            isBuyer\n        }\n    }\n"): (typeof documents)["\n    query GetTrades($data: GetTradeInput!) {\n        getTrades(data: $data) {\n            cryptoPortfolio {\n                id\n                name\n                exchanges\n            }\n            time\n            price\n            qty\n            quoteQty\n            commission\n            commissionAsset\n            isBuyer\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetExpenseCategories(\n        $name: String\n        $startDate: DateTime\n        $endDate: DateTime\n        $month: Int\n        $year: Int\n    ) {\n        getExpenseCategories(name: $name) {\n            color\n            description\n            name\n            id\n            countExpenses\n            totalSpentAmounts(startDate: $startDate, endDate: $endDate) {\n                amount\n                month\n                year\n            }\n            monthlyTargets(month: $month, year: $year) {\n                month\n                year\n                target\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetExpenseCategories(\n        $name: String\n        $startDate: DateTime\n        $endDate: DateTime\n        $month: Int\n        $year: Int\n    ) {\n        getExpenseCategories(name: $name) {\n            color\n            description\n            name\n            id\n            countExpenses\n            totalSpentAmounts(startDate: $startDate, endDate: $endDate) {\n                amount\n                month\n                year\n            }\n            monthlyTargets(month: $month, year: $year) {\n                month\n                year\n                target\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateExpenseCategory($data: CreateExpenseCategoryInput!) {\n        createExpenseCategory(data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateExpenseCategory($data: CreateExpenseCategoryInput!) {\n        createExpenseCategory(data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateExpenseCategory(\n        $id: String!\n        $data: UpdateExpenseCategoryInput!\n    ) {\n        updateExpenseCategory(id: $id, data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateExpenseCategory(\n        $id: String!\n        $data: UpdateExpenseCategoryInput!\n    ) {\n        updateExpenseCategory(id: $id, data: $data) {\n            color\n            description\n            name\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RemoveExpenseCategory($id: String!) {\n        removeExpenseCategory(id: $id) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation RemoveExpenseCategory($id: String!) {\n        removeExpenseCategory(id: $id) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetMonthlyTargets($categoryId: String!, $month: Int, $year: Int) {\n        getMonthlyTargets(categoryId: $categoryId, month: $month, year: $year) {\n            target\n            month\n            year\n        }\n    }\n"): (typeof documents)["\n    query GetMonthlyTargets($categoryId: String!, $month: Int, $year: Int) {\n        getMonthlyTargets(categoryId: $categoryId, month: $month, year: $year) {\n            target\n            month\n            year\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateMonthlyTarget($data: CreateMonthlyTargetInput!) {\n        createMonthlyTarget(data: $data) {\n            categoryId\n        }\n    }\n"): (typeof documents)["\n    mutation CreateMonthlyTarget($data: CreateMonthlyTargetInput!) {\n        createMonthlyTarget(data: $data) {\n            categoryId\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateMonthlyTarget(\n        $id: String!\n        $data: UpdateMonthlyTargetInput!\n    ) {\n        updateMonthlyTarget(id: $id, data: $data) {\n            categoryId\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateMonthlyTarget(\n        $id: String!\n        $data: UpdateMonthlyTargetInput!\n    ) {\n        updateMonthlyTarget(id: $id, data: $data) {\n            categoryId\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetExpenses($startDate: DateTime, $endDate: DateTime) {\n        getExpenses(startDate: $startDate, endDate: $endDate) {\n            id\n            category {\n                id\n                color\n                name\n            }\n            transaction {\n                id\n                amount\n                spentAmount\n                description\n                createdAt\n                bank {\n                    name\n                }\n            }\n            createdAt\n            description\n            amount\n            name\n        }\n    }\n"): (typeof documents)["\n    query GetExpenses($startDate: DateTime, $endDate: DateTime) {\n        getExpenses(startDate: $startDate, endDate: $endDate) {\n            id\n            category {\n                id\n                color\n                name\n            }\n            transaction {\n                id\n                amount\n                spentAmount\n                description\n                createdAt\n                bank {\n                    name\n                }\n            }\n            createdAt\n            description\n            amount\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetSuggestedExpenses($data: SuggestExpenseInput!) {\n        getSuggestedExpenses(data: $data) {\n            amount\n            name\n            bankTransactionId\n            categoryId\n            description\n        }\n    }\n"): (typeof documents)["\n    query GetSuggestedExpenses($data: SuggestExpenseInput!) {\n        getSuggestedExpenses(data: $data) {\n            amount\n            name\n            bankTransactionId\n            categoryId\n            description\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateExpense($data: CreateExpenseInput!) {\n        createExpense(data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n"): (typeof documents)["\n    mutation CreateExpense($data: CreateExpenseInput!) {\n        createExpense(data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateExpense($id: String!, $data: UpdateExpenseInput!) {\n        updateExpense(id: $id, data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateExpense($id: String!, $data: UpdateExpenseInput!) {\n        updateExpense(id: $id, data: $data) {\n            id\n            description\n            amount\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RemoveExpense($id: String!) {\n        removeExpense(id: $id) {\n            id\n            description\n            amount\n            name\n        }\n    }\n"): (typeof documents)["\n    mutation RemoveExpense($id: String!) {\n        removeExpense(id: $id) {\n            id\n            description\n            amount\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RemoveExpenses($ids: [String!]!) {\n        removeExpenses(ids: $ids)\n    }\n"): (typeof documents)["\n    mutation RemoveExpenses($ids: [String!]!) {\n        removeExpenses(ids: $ids)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetMembershipPlans {\n        getMembershipPlans {\n            id\n            name\n            description\n            createdAt\n            updatedAt\n            prices {\n                id\n                billingCycle {\n                    frequency\n                    interval\n                }\n                trialPeriod {\n                    frequency\n                    interval\n                }\n                unitPrice {\n                    amount\n                    currencyCode\n                }\n            }\n            membershipFeatures {\n                feature {\n                    type\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetMembershipPlans {\n        getMembershipPlans {\n            id\n            name\n            description\n            createdAt\n            updatedAt\n            prices {\n                id\n                billingCycle {\n                    frequency\n                    interval\n                }\n                trialPeriod {\n                    frequency\n                    interval\n                }\n                unitPrice {\n                    amount\n                    currencyCode\n                }\n            }\n            membershipFeatures {\n                feature {\n                    type\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetMyMembershipSubscriptions {\n        myMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n            paymentTransactions {\n                id\n                amount\n                currency\n                status\n                createdAt\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetMyMembershipSubscriptions {\n        myMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n            paymentTransactions {\n                id\n                amount\n                currency\n                status\n                createdAt\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetMyActiveMembershipSubscriptions {\n        myActiveMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetMyActiveMembershipSubscriptions {\n        myActiveMembershipSubscriptions {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n            plan {\n                id\n                name\n                description\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CancelMembershipSubscription($id: String!) {\n        cancelPaddleSubscription(id: $id) {\n            id\n            status\n            endDate\n        }\n    }\n"): (typeof documents)["\n    mutation CancelMembershipSubscription($id: String!) {\n        cancelPaddleSubscription(id: $id) {\n            id\n            status\n            endDate\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateMembershipSubscription(\n        $id: String!\n        $data: UpdateSubscriptionDto!\n    ) {\n        updateMembershipSubscription(id: $id, data: $data) {\n            id\n            status\n            planId\n            endDate\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateMembershipSubscription(\n        $id: String!\n        $data: UpdateSubscriptionDto!\n    ) {\n        updateMembershipSubscription(id: $id, data: $data) {\n            id\n            status\n            planId\n            endDate\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation ReactivatePaddleSubscription($id: String!) {\n        reactivatePaddleSubscription(id: $id) {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation ReactivatePaddleSubscription($id: String!) {\n        reactivatePaddleSubscription(id: $id) {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription OnMembershipSubscriptionUpdated {\n        onMembershipSubscriptionUpdated {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    subscription OnMembershipSubscriptionUpdated {\n        onMembershipSubscriptionUpdated {\n            id\n            userId\n            planId\n            status\n            startDate\n            endDate\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetPaymentMethods {\n        getPaymentMethods {\n            id\n            provider\n            paddlePaymentMethod {\n                id\n                customerId\n                addressId\n                businessId\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetPaymentMethods {\n        getPaymentMethods {\n            id\n            provider\n            paddlePaymentMethod {\n                id\n                customerId\n                addressId\n                businessId\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetEventCategories {\n        getEventCategories {\n            id\n            name\n            color\n        }\n    }\n"): (typeof documents)["\n    query GetEventCategories {\n        getEventCategories {\n            id\n            name\n            color\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateEventCategory($data: CreateEventCategoryInput!) {\n        createEventCategory(data: $data) {\n            id\n            name\n            color\n        }\n    }\n"): (typeof documents)["\n    mutation CreateEventCategory($data: CreateEventCategoryInput!) {\n        createEventCategory(data: $data) {\n            id\n            name\n            color\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateEventCategory($id: Int!, $data: UpdateEventCategoryInput!) {\n        updateEventCategory(id: $id, data: $data) {\n            id\n            name\n            color\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateEventCategory($id: Int!, $data: UpdateEventCategoryInput!) {\n        updateEventCategory(id: $id, data: $data) {\n            id\n            name\n            color\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RemoveEventCategory($id: Int!) {\n        removeEventCategory(id: $id) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation RemoveEventCategory($id: Int!) {\n        removeEventCategory(id: $id) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetRecurrenceTemplates {\n        getRecurrenceTemplates {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n            events {\n                id\n                name\n                description\n                startDate\n                endDate\n                allDay\n                color\n                categoryId\n                reminderMinutes\n                category {\n                    id\n                    name\n                    color\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetRecurrenceTemplates {\n        getRecurrenceTemplates {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n            events {\n                id\n                name\n                description\n                startDate\n                endDate\n                allDay\n                color\n                categoryId\n                reminderMinutes\n                category {\n                    id\n                    name\n                    color\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetRecurrenceTemplate($id: Int!) {\n        getRecurrenceTemplate(id: $id) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetRecurrenceTemplate($id: Int!) {\n        getRecurrenceTemplate(id: $id) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateRecurrenceTemplate(\n        $id: Int!\n        $data: UpdateEventRecurrenceInput!\n    ) {\n        updateRecurrenceTemplate(id: $id, data: $data) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateRecurrenceTemplate(\n        $id: Int!\n        $data: UpdateEventRecurrenceInput!\n    ) {\n        updateRecurrenceTemplate(id: $id, data: $data) {\n            id\n            type\n            interval\n            daysOfWeek\n            dayOfMonth\n            weekOfMonth\n            dayOfWeek\n            endDate\n            endCount\n            userId\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteRecurrenceTemplate($id: Int!) {\n        deleteRecurrenceTemplate(id: $id) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteRecurrenceTemplate($id: Int!) {\n        deleteRecurrenceTemplate(id: $id) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetEvents($startDate: DateTime, $endDate: DateTime) {\n        getEvents(startDate: $startDate, endDate: $endDate) {\n            id\n            name\n            startDate\n            endDate\n            allDay\n            color\n            description\n            category {\n                id\n                name\n                color\n            }\n            recurrence {\n                type\n                interval\n                daysOfWeek\n                dayOfMonth\n                weekOfMonth\n                dayOfWeek\n                endDate\n                endCount\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetEvents($startDate: DateTime, $endDate: DateTime) {\n        getEvents(startDate: $startDate, endDate: $endDate) {\n            id\n            name\n            startDate\n            endDate\n            allDay\n            color\n            description\n            category {\n                id\n                name\n                color\n            }\n            recurrence {\n                type\n                interval\n                daysOfWeek\n                dayOfMonth\n                weekOfMonth\n                dayOfWeek\n                endDate\n                endCount\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateEvent($data: CreateEventInput!) {\n        createEvent(data: $data) {\n            id\n            name\n            startDate\n            endDate\n            category {\n                id\n            }\n            recurrence {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation CreateEvent($data: CreateEventInput!) {\n        createEvent(data: $data) {\n            id\n            name\n            startDate\n            endDate\n            category {\n                id\n            }\n            recurrence {\n                id\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateEvent($id: Int!, $data: UpdateEventInput!) {\n        updateEvent(id: $id, data: $data) {\n            id\n            name\n            startDate\n            endDate\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateEvent($id: Int!, $data: UpdateEventInput!) {\n        updateEvent(id: $id, data: $data) {\n            id\n            name\n            startDate\n            endDate\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RemoveEvent($id: Int!) {\n        removeEvent(id: $id) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation RemoveEvent($id: Int!) {\n        removeEvent(id: $id) {\n            id\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;