apiVersion: v1
kind: Secret
metadata:
  name: xela-secrets
type: Opaque
stringData:
  DATABASE_USER: "postgre"
  DATABASE_PASSWORD: "abcd1234"
  DATABASE_URL: "postgresql://postgre:abcd1234@database:5432/xela?schema=public"
  CASSANDRA_USERNAME: "cassandra"
  CASSANDRA_PASSWORD: "abcd1234"
  OTP_KEY: "JBSWY3DPEHPK3PXP"
  JWT_SECRET: "xelaqdtjlz"
  JWT_AT_EXP_TIME: "1d"
  JWT_RT_EXP_TIME: "360d"
  BANK_API_URL: "https://oauth.casso.vn"
  BACKEND_SENTRY_AUTH_TOKEN: "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"
  CRYPTO_PORTFOLIO_MASTER_KEY: "pRlbqjx9R1-uqcEQN_1gdH5O2Gq7zjkfV0kS8uW2FfQ="
  REDIS_PASSWORD: "redis" 