query GetBankTransactions {
    getBankTransactions {
        id
        amount
        spentAmount
        createdAt
        description
        bank {
            name
        }
    }
}

mutation CreateBankTransaction($data: CreateBankTransactionInput!) {
    createBankTransaction(data: $data) {
        id
        amount
        description
        createdAt
        bankId
    }
}